export default {
  lottie: {
    splash: require('../assets/lottie/splash.json'),
    loading: require('../assets/lottie/loading.json'),
    loading2: require('../assets/lottie/loading2.json'),
    like: require('../assets/lottie/like.json'),
    likeN: require('../assets/lottie/like_n.json'),
    hate: require('../assets/lottie/hate.json'),
    hateN: require('../assets/lottie/hate_n.json'),
  },
  gif: {
    error404: require('../assets/images/gif/404-error.gif'),
    boyReadingFinancialLiteratureBook: require('../assets/images/gif/boy-reading-financial-literature-book.gif'),
    businessContacts: require('../assets/images/gif/business-contacts.gif'),
    businessPeopleFightForTrophy: require('../assets/images/gif/business-people-fight-for-trophy.gif'),
    businessmanDoingBudgetPlanning: require('../assets/images/gif/businessman-doing-budget-planning.gif'),
    computerSecurity: require('../assets/images/gif/computer-security.gif'),
    contactIsEmpty: require('../assets/images/gif/contact-is-empty.gif'),
    cvAnalysis: require('../assets/images/gif/cv-analysis.gif'),
    employeeCard: require('../assets/images/gif/employee-card.gif'),
    faceIdLock: require('../assets/images/gif/face-id-lock.gif'),
    folderIsEmpty: require('../assets/images/gif/folder-is-empty.gif'),
    girlGettingFundsProtection: require('../assets/images/gif/girl-getting-funds-protection.gif'),
    identityCard: require('../assets/images/gif/identity-card.gif'),
    manFacingWebsiteError: require('../assets/images/gif/man-facing-website-error.gif'),
    mobileSystemUpdate: require('../assets/images/gif/mobile-system-update.gif'),
    noMessage: require('../assets/images/gif/no-message.gif'),
    noResultSearch: require('../assets/images/gif/no-result-search.gif'),
    websiteUnderConstruction: require('../assets/images/gif/website-under-construction.gif'),
    womanSendingMessageViaApp: require('../assets/images/gif/woman-sending-message-via-app.gif'),
    womanSendingSecureMessages: require('../assets/images/gif/woman-sending-secure-messages.gif'),
  },
  png: {
    faceGuide1: require('../assets/images/png/faceGuide1.png'),
    faceGuide2: require('../assets/images/png/faceGuide2.png'),
    faceGuide3: require('../assets/images/png/faceGuide3.png'),
    idGuide1: require('../assets/images/png/idGuide1.png'),
    idGuide2: require('../assets/images/png/idGuide2.png'),
    idGuide3: require('../assets/images/png/idGuide3.png'),
    profile: require('../assets/images/png/profile.png'),
    residenceFaceGuide: require('../assets/images/png/residenceFaceGuide.png'),
    residenceIdGuide: require('../assets/images/png/residenceIdGuide.png'),
    noImage: require('../assets/images/png/noImage.png'),
  },
  testImg: {
    androboi: require('../assets/images/testImg/androboi.png'),
    doraemon: require('../assets/images/testImg/doraemon.png'),
    holmes: require('../assets/images/testImg/holmes.webp'),
    ironman: require('../assets/images/testImg/ironman.jpeg'),
    minions: require('../assets/images/testImg/minions.png'),
    yuri: require('../assets/images/testImg/yuri.jpeg'),
  },
}
